wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1720366741
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.17.4
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
